### ISSUE TITLE
ArrayList and Team Setup

### ISSUE THREAD

**Issue by Gabrielboudreau** [Gabrielboudreau/CSATeam#19] opened 2022-10-18 17:38 UTC
ArrayList (Individual): 

Jay:

Gabe: [ArrayList](https://gabrielboudreau.github.io/CSPAT1/2022/10/07/arrayList.html)

Rohan:

Kinish:

Team Repos:

[FrontEnd](https://github.com/Gabrielboudreau/frontTeamCSA)

[BackEnd](https://github.com/Gabrielboudreau/CSATeam)

**Comment by rjawesome** [comment] 2022-10-23 23:59
Duplicate of other issue

**Closed as not planned by rjawesome** 2022-10-23 23:59 UTC
